### ISSUE TITLE
The date on news page is misaligned

### ISSUE THREAD

**Issue by vixalien** [jimmac/cairographics.org#1]
The dates are not aligned. may I suggest using tabular numeric characters so that they all look "in line".

```css
ul.news .date {
  font-feature-settings: "tnum";
}
```
